### ISSUE TITLE
Back button does not trigger a count update

### ISSUE THREAD

**Issue by dlew** [dlew/displate-inventory-extension#6]
# Repro

1. Visit an individual LE page (e.g. https://displate.com/limited-edition/displate/5832319)
2. Click a different LE from the bottom.
3. Click "back".

Expected: the counter at the top should match the current LE at all times.

Actual: the counter matches the 2nd LE you clicked, not the first.

**Comment by Yesitics** [comment]
Opened a pull request to fix this issue. The changes include handling the 'popstate' event to manage the 'units' and 'added-inv-data' classes, ensuring proper behavior during back/forward navigation.
